services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV: prod
        NEXT_PUBLIC_API_BASE_URL: https://api.scholarai.me
        NEXT_PUBLIC_DEV_API_URL: http://localhost:8989
        NEXT_PUBLIC_DOCKER_BACKEND_URL: http://scholar-api-gateway:8989      
    container_name: scholar-frontend

    # 🏷️ Add metadata labels for cleanup & observability
    labels:
      service: "frontend"
      maintainer: "ScholarAI <dev@scholarai.local>"
      version: "0.0.1-SNAPSHOT"
      description: "Next.js Frontend for ScholarAI"
    env_file:
      - /opt/scholarai/envs/frontend.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV=prod
      - NEXT_PUBLIC_API_BASE_URL=https://api.scholarai.me
      - NEXT_PUBLIC_DEV_API_URL=http://localhost:8989
      - NEXT_PUBLIC_DOCKER_BACKEND_URL=http://scholar-api-gateway:8989
    networks:
      - scholarai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
